import React from 'react';
import { BookA, Shield, Key, Database, ChevronRight, Hash, Network, Scale } from 'lucide-react';
import Link from 'next/link';

export const metadata = {
  title: 'Glossary of Cryptographic Governance Terms | AGEI Docs',
  description: 'Foundational technical terms, cryptographic primitives, and architectural concepts underpinning AGEI.',
};

export default function GlossaryPage() {
  
  const glossaryTerms = [
    {
      letter: 'A',
      terms: [
        {
          term: 'AI Governance Evidence Infrastructure (AGEI)',
          definition: 'An architectural layer that captures, seals, links, stores, and retrieves verifiable governance evidence across the AI lifecycle [92, 162]. AGEI operates independently of operational MLOps, SIEM, or GRC platforms to convert passive human policy into active, cryptographically verifiable proof of control execution [93, 94, 171].'
        },
        {
          term: 'Agentic Action Risk',
          definition: 'The operational risk associated with autonomous, tool-using AI agents that plan, retrieve data, interact with APIs, and modify external system state under delegated authority [146, 449, 450]. This contrasts with content risk, which is limited to conversational outputs generated by static LLM chat assistants [449, 450].'
        },
        {
          term: 'Anchor / Anchoring',
          definition: 'The process of publishing a cryptographic digest (such as a Merkle Root hash of a receipt batch) to an immutable ledger, write-once-read-many (WORM) storage, or cloud Hardware Security Module (HSM) [491, 502]. Anchoring establishes a non-repudiable proof-of-time and protects against retroactive modification of the historical evidence graph [99, 491].'
        },
        {
          term: 'Assurance Profile',
          definition: <>A standardized classification of evidence strength that defines the maturity and cryptographic rigor of captured proof [131, 181]. The architecture supports three progressive profiles:
            <ul className="list-disc list-inside mt-2 space-y-1 ml-2 text-sm">
              <li><strong>Profile 1 (Internal Evidence):</strong> Captures lightweight operational logs, basic policy definitions, and state transitions for internal accountability [132, 133].</li>
              <li><strong>Profile 2 (Regulated Evidence):</strong> Implements signed lifecycle receipts, machine-evaluable gate constraints, and portable audit packs for external audit readiness [132, 134].</li>
              <li><strong>Profile 3 (Forensic Evidence):</strong> Enforces hardware-backed signatures, Merkle batch anchoring, cryptographic erasure, legal holds, and courtroom-ready verification workflows [132, 135].</li>
            </ul>
          </>
        },
        {
          term: 'Audit Pack',
          definition: 'A self-contained, inspection-ready collection of cryptographically signed receipts, policy evaluations, and lifecycle snapshots materialized on-demand [100, 142, 486, 497]. Governed by a signed manifest, an audit pack allows a skeptical external verifier to reconstruct and validate a lifecycle chain completely offline [129, 484, 495].'
        },
        {
          term: 'Authority Attenuation',
          definition: 'The policy-enforced process of progressively narrowing the operational permissions, database boundaries, or transaction limits delegated down a multi-agent orchestration tree [26, 148]. Attenuation ensures that child agents can never inherit or execute actions exceeding those authorized by the delegating human principal [26, 148, 201].'
        }
      ]
    },
    {
      letter: 'C',
      terms: [
        {
          term: 'Canonicalization (RFC 8785)',
          definition: 'The process of normalising structured JSON payloads into a deterministic, whitespace-free byte stream with sorted keys prior to computing a cryptographic hash or signature [2, 111, 488]. Canonicalization eliminates serialization ambiguities across different development environments, ensuring identical semantic content always generates the identical hash digest [243, 488].'
        },
        {
          term: 'Capsule (Evidence Capsule)',
          definition: 'The complete, expanded payload representing a governed AI event, containing full rule execution outputs, prompt context digests, environment SBOMs, or raw database references [12, 122, 167]. Under the Lazy Capsule Materialization pattern, capsules are only generated on demand, while lightweight receipts are committed continuously [101, 167, 318].'
        },
        {
          term: 'Cognitive Insight Audit Framework (CIAF)',
          definition: 'An AI governance evidence framework for representing, evaluating, and preserving governed AI events as structured, verifiable records [166]. CIAF defines the policy-to-proof sequence: converting enterprise intent into versioned rules, enforcing them at gates, and persisting results in a tamper-evident evidence graph [106, 114].'
        },
        {
          term: 'Crypto-Shredding (Privacy Rights Enforcement)',
          definition: 'The intentional, irreversible destruction of a specific subject-level symmetric decryption key (public.subject_encryption_keys) to fulfill GDPR Article 17 "Right to be Forgotten" mandates [72, 111, 113]. Shredding the key renders the encrypted payload data (public.receipt_encrypted_content) permanently unrecoverable (effectively erased) while leaving the chronological hash chain and outer Merkle batch ledger fully verifiable [72, 111, 285].'
        }
      ]
    },
    {
      letter: 'D',
      terms: [
        {
          term: 'Denial Receipt',
          definition: 'A cryptographically signed receipt emitted by a runtime or lifecycle gate when a policy rule is violated, blocking a proposed action [117, 323, 460]. A denial receipt records the attempted action, the acting principal, the violated rule ID, and the cryptographic context hash, proving to auditors that governance policies actively constrained system operations [127, 323, 460].'
        },
        {
          term: 'Deny-by-Default',
          definition: 'A security posture where an agent tool call or model deployment is systematically blocked at the runtime boundary unless the executing context possesses a cryptographically valid, active authorization token and passes all policy rules [120, 321, 460].'
        },
        {
          term: 'Dual-Layer Provenance',
          definition: <>An artifact verification model combining explicit and forensic layers to secure AI-generated outputs after they leave the runtime boundary [390, 391]:
            <ul className="list-disc list-inside mt-2 space-y-1 ml-2 text-sm">
              <li><strong>Explicit Watermarking:</strong> Direct signaling via visual overlays, metadata tags, or QR codes to allow low-friction, first-pass verification [392, 395].</li>
              <li><strong>Forensic Fingerprinting:</strong> A fallback, content-aware verification mechanism (such as anchor shingling for text) that persists even if visual marks or metadata are stripped, retyped, or screenshotted [392, 398, 399].</li>
            </ul>
          </>
        },
        {
          term: 'Dual-State Hashing',
          definition: 'The practice of generating two linked content hashes for an exported artifact: a pre-watermark hash of the pristine generated content, and a post-watermark hash of the final, released file [158, 396]. This dual attestation mathematically proves that a distributed file corresponds to a specific, governed model execution event [158, 396, 409].'
        }
      ]
    },
    {
      letter: 'E',
      terms: [
        {
          term: 'Ed25519',
          definition: 'A public-key signature scheme utilizing the Edwards-curve Digital Signature Algorithm (EdDSA) over Curve25519 [3, 489, 505]. Specified in RFC 8032, Ed25519 is the default signing algorithm for AGEI receipts due to its high verification speed, compact 64-byte signature size, resistance to side-channel attacks, and deterministic signing process (which eliminates per-signature random number generation) [3, 484, 489].'
        },
        {
          term: 'Evidence-Bearing Decision',
          definition: 'Any control event, such as a validation gate approval or a human policy override, that is committed to WORM storage with explicit signatures, timestamps, and logic justifications, transforming an administrative event into legal-grade evidence [117, 120].'
        },
        {
          term: 'Evidence Control Plane',
          definition: 'The distributed software and middleware runtime that intercept operational inputs, evaluate policy rules, verify delegation keys, and generate signed receipts before allowing tools to execute [93, 147, 452].'
        },
        {
          term: 'Evidence Graph',
          definition: 'The relational network of hashes, receipts, parent-child delegation chains, and lifecycle object links stored in the database [114, 251, 257]. By tracing edges in this graph, an auditor can reconstruct the unbroken history of an AI system from training dataset onboarding down to an individual model output [96, 251].'
        },
        {
          term: 'Evidence Vault (Tamper-Evident Evidence Vault)',
          definition: 'The hardware-secured, append-only custody layer designed to canonicalize, hash, sign, link, and store governance receipts and payloads [139, 481, 502]. It isolates and protects evidence integrity over long retention cycles, even in environments where the primary operational database is compromised or administratively modified [478, 481, 492].'
        },
        {
          term: 'Explicit Watermarking',
          definition: 'A direct mechanism for embedding traceable markers (such as steganographic payloads or structural metadata) directly into exported documents or files to signal origin and link back to an upstream release receipt [168, 392, 395].'
        }
      ]
    },
    {
      letter: 'F',
      terms: [
        {
          term: 'Forensic Fingerprinting',
          definition: 'A non-invasive, content-based extraction process (such as zone-based shingle-hashing) used to identify and verify AI-generated files after distribution [159, 398]. Fingerprinting does not modify the output file, allowing origin matching even if the artifact has been heavily cropped, compressed, or screenshotted [399, 411].'
        },
        {
          term: 'Five Governance Planes',
          definition: <>An architectural framework for securing autonomous agent actions by routing every tool invocation through five independent control layers [147, 451, 452]:
            <ul className="list-disc list-inside mt-2 space-y-1 ml-2 text-sm">
              <li><strong>Identity Plane:</strong> Resolves the active user session and delegating human principal (agent_sessions) [147, 454].</li>
              <li><strong>Policy Plane:</strong> Evaluates the active rulesets in force (policy_rules) [147, 454].</li>
              <li><strong>Privilege Plane:</strong> Verifies scoped authority and JIT elevation states (agent_delegations) [147, 455].</li>
              <li><strong>Execution Plane:</strong> Enforces parameter boundaries via mediated tool wrappers (agent_tool_definitions) [147, 455].</li>
              <li><strong>Evidence Plane:</strong> Commits signed action or denial receipts (receipts) [147, 456].</li>
            </ul>
          </>
        }
      ]
    },
    {
      letter: 'G',
      terms: [
        {
          term: 'Governance Gates',
          definition: 'Enforceable, logical checkpoints placed at critical model lifecycle and agent runtime transitions [108, 109, 168]. Gates ingest versioned policy rules, evaluate active resource parameters, and produce deterministic outcomes (Approve, Deny, Escalate, Inspect) before permitting state changes [117, 118, 321, 352].'
        },
        {
          term: 'Governance Tier Equation',
          definition: 'A risk-modeling formula that evaluates an agent\'s functional role, delegated authority scope, data context access, memory persistency, and autonomy tier to calculate its required compliance and evidence collection burden ($G_T$) [200, 220].'
        }
      ]
    },
    {
      letter: 'H',
      terms: [
        {
          term: 'Hash-Only Ingestion (Privacy Boundary)',
          definition: 'A sanitization process used during Shadow AI discovery where raw, unencrypted employee prompts or pasted data are intercepted, analyzed for metadata out-of-band, converted to a SHA-256 hash, and immediately shredded [42, 539, 550]. This allows security teams to search for data leaks without creating a massive secondary GDPR storage liability [539, 540, 550].'
        },
        {
          term: 'Human-in-the-Loop (HITL) Gate',
          definition: 'An escalation control point where a high-risk agent transaction is suspended until an authorized human principal reviews the context, justifies the action, and signs off using an enterprise cryptographic key [126, 128].'
        }
      ]
    },
    {
      letter: 'L',
      terms: [
        {
          term: 'Lazy Capsule Materialization (LCM)',
          definition: 'The core design pattern of the CIAF lifecycle model [167, 338]. It balances system performance with audit rigor by continuously capturing lightweight, sub-second transaction receipts [101, 318, 349]. The assembly of heavier evidence capsules (full datasets, detailed rule traces, and verification logs) is deferred until a specific gate threshold, audit demand, or security incident triggers expansion [101, 167, 318, 349].'
        },
        {
          term: 'Legal Hold',
          definition: 'An administrative state applied to specific vault objects or receipts that temporarily suspends default retention deletion schedules [135, 143, 500]. A legal hold guarantees that evidence remains frozen and immutable during pending litigation or regulatory inquiries [143, 500].'
        },
        {
          term: 'Lifecycle Receipt',
          definition: 'An immutable, self-contained JSON record capturing the cryptographic state of a single lifecycle transition (e.g., dataset ingestion, training, validation, or release) [96, 169, 314, 345]. Every receipt is canonicalized and signed using Ed25519 to support offline verification [264, 314, 345].'
        }
      ]
    },
    {
      letter: 'M',
      terms: [
        {
          term: 'Merkle Batching',
          definition: 'The process of grouping multiple receipt hashes into a hierarchical cryptographic Merkle Tree [142, 490]. The vault publishes the top-level Merkle Root hash to an immutable log, enabling compact "Merkle Proofs" that mathematically prove any single receipt was included in that batch without requiring the transmission of the surrounding records [10, 142, 490].'
        },
        {
          term: 'Multimodal Concept Memory (MCM)',
          definition: 'A neuro-symbolic memory engine that maps long-horizon interactions to an explicit 8-lobe semantic bottleneck [516, 519, 523]. It consolidates, prunes, and hashes cognitive states over long horizons to mitigate cognitive tampering in autonomous systems [515, 520].'
        }
      ]
    },
    {
      letter: 'P',
      terms: [
        {
          term: 'Pre-Action Proof-Carrying Bundle',
          definition: 'A cryptographically bound data block generated out-of-band by the Sidecar SDK before an agent invokes a tool [121, 149, 283]. It contains the active context hash, policy check receipt ID, delegation reference, and gate evaluation signature, proving the agent\'s authority is active and valid prior to execution [121, 122, 149, 150].'
        },
        {
          term: 'Provenance Gate',
          definition: 'The initial governance control point that verifies the lineage, acquisition methods, consent records, and licensing parameters of datasets before they can be ingested into model training pipelines [109, 322, 324].'
        }
      ]
    },
    {
      letter: 'R',
      terms: [
        {
          term: 'Receipt Batch (Merkle Tree Root)',
          definition: 'A chronological grouping of receipts hashed into a single parent cryptographic root to optimize vault indexing, anchoring, and offline verification speed [9, 10, 142].'
        },
        {
          term: 'Row-Level Security (RLS)',
          definition: 'The database access control architecture used to enforce tenant isolation in multi-tenant installations [251, 258]. RLS ensures that database operators or adjacent tenant accounts can never query or mutate another organization\'s policy sets, keys, or receipts [251, 255].'
        },
        {
          term: 'Runtime Gate',
          definition: 'An active control wrapper placed around sensitive model inference paths or external agent tool execution to validate permissions and rules before execution [109, 322, 324, 449].'
        }
      ]
    },
    {
      letter: 'S',
      terms: [
        {
          term: 'SHA-256',
          definition: 'A secure cryptographic hash algorithm that compresses an arbitrary length input into a fixed, deterministic 32-byte (256-bit) digest [237, 242, 489]. Within AGEI, SHA-256 is the standard content hashing standard, creating tamper-evident fingerprints for all payloads, files, and database states [237, 242, 489].'
        },
        {
          term: 'Shadow AI',
          definition: 'Any unmanaged or unsanctioned use of public AI tools, browser-embedded copilots, or third-party APIs by employees outside the organization\'s approved governance perimeter [156, 169, 531, 533].'
        },
        {
          term: 'Sidecar SDK',
          definition: 'The out-of-band, language-agnostic software development kit that intercepts model and agent activity, canonicalizes payloads (RFC 8785), signs them (Ed25519), and commits them to the evidence vault asynchronously without impacting execution latency [522, 528].'
        }
      ]
    },
    {
      letter: 'V',
      terms: [
        {
          term: 'Validation Gate',
          definition: 'The governance checkpoint that evaluates a model\'s technical testing, safety thresholds, and bias checks against the versioned corporate policy before allowing promotion to release states [109, 125, 322, 324].'
        },
        {
          term: 'Verification Job',
          definition: 'An automated, repeatable workflow that reconstructs an evidence package and cryptographically tests its content hashes, signature validity, Merkle batch inclusion, and predecessor chain integrity to prove its defensibility [100, 143, 257, 494].'
        }
      ]
    },
    {
      letter: 'W',
      terms: [
        {
          term: 'WORM (Write-Once-Read-Many)',
          definition: 'An immutable storage class that strictly limits unauthorized modification, overwriting, or deletion of recorded bytes [143, 167, 500]. All high-assurance receipts, gate evaluations, and vault objects are committed to WORM-configured files to support mathematical defensibility [143, 167, 500].'
        }
      ]
    }
  ];

  return (
    <div className="container mx-auto px-4 py-12 max-w-6xl">
      <div className="mb-10 border-b border-border pb-8">
        <div className="flex items-center gap-2 text-sm text-muted-foreground mb-4">
          <Link href="/docs" className="hover:text-primary transition-colors">Documentation</Link>
          <span>/</span>
          <span className="text-foreground font-medium">Glossary</span>
        </div>
        <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight mb-4 flex items-center gap-3">
          <BookA className="h-10 w-10 text-primary" />
          Glossary of Cryptographic Governance Terms
        </h1>
        <div className="text-sm font-mono text-muted-foreground bg-muted inline-block px-4 py-2 rounded-lg border border-border">
          <span className="block md:inline mr-4"><strong>CognitiveInsight.ai</strong> — Developer Documentation Center</span>
          <span className="block md:inline mr-4"><strong>Author:</strong> Denzil Greenwood</span>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
        
        {/* Main Content (Glossary) */}
        <div className="lg:col-span-3 space-y-12">
          
          <div className="bg-muted p-6 rounded-2xl border border-border shadow-sm mb-12">
            <h2 className="text-xl font-bold text-foreground mb-3 flex items-center gap-2">
              <Shield className="h-5 w-5 text-primary" />
              Core Reference
            </h2>
            <p className="text-muted-foreground leading-relaxed text-sm">
              This glossary defines the foundational technical terms, cryptographic primitives, and architectural concepts underpinning the AI Governance Evidence Infrastructure (AGEI) and the Cognitive Insight Audit Framework (CIAF-LCM). It serves as an authoritative reference for systems architects, compliance engineers, security officers, and external auditors.
            </p>
          </div>

          <div className="space-y-12">
            {glossaryTerms.map((section, idx) => (
              <section key={idx} id={`letter-${section.letter}`} className="scroll-mt-24">
                <div className="flex items-center gap-4 mb-6">
                  <div className="h-12 w-12 rounded-full bg-primary/10 text-primary flex items-center justify-center text-2xl font-black border border-primary/20 shrink-0">
                    {section.letter}
                  </div>
                  <div className="h-px bg-border flex-1"></div>
                </div>
                
                <div className="space-y-6">
                  {section.terms.map((item, itemIdx) => (
                    <div key={itemIdx} className="bg-card border border-border rounded-xl p-6 shadow-sm hover:shadow-md transition-shadow">
                      <h3 className="text-xl font-bold text-foreground mb-3">{item.term}</h3>
                      <div className="text-muted-foreground text-sm leading-relaxed">
                        {item.definition}
                      </div>
                    </div>
                  ))}
                </div>
              </section>
            ))}
          </div>
        </div>

        {/* Sidebar / Quick Nav */}
        <div className="hidden lg:block">
          <div className="sticky top-24 space-y-6">
            <div className="bg-card border border-border rounded-xl p-5 shadow-sm">
              <h3 className="font-bold text-sm uppercase tracking-wider text-muted-foreground mb-4 border-b border-border pb-2">
                Quick Navigation
              </h3>
              <div className="flex flex-wrap gap-2">
                {glossaryTerms.map((section, idx) => (
                  <a 
                    key={idx} 
                    href={`#letter-${section.letter}`}
                    className="w-8 h-8 rounded-md bg-muted hover:bg-primary/10 text-foreground hover:text-primary flex items-center justify-center font-bold text-sm transition-colors border border-border hover:border-primary/30"
                  >
                    {section.letter}
                  </a>
                ))}
              </div>
            </div>

            <div className="bg-primary/5 border border-primary/20 rounded-xl p-5">
              <h3 className="font-bold text-sm uppercase tracking-wider text-primary mb-3">
                Strategic Overview
              </h3>
              <p className="text-xs text-muted-foreground mb-3 leading-relaxed">
                This glossary bridges the gap between deep cryptographic engineering and high-stakes risk liabilities, translating technical primitives into clear, risk-mitigated business outcomes.
              </p>
              <ul className="text-xs text-muted-foreground space-y-2 list-disc list-inside">
                <li>Cryptographic Primitives</li>
                <li>AI Governance Loop</li>
                <li>Agentic Governance</li>
                <li>Perimeter & Data Rights</li>
              </ul>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
}
